name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: HoshinoNeko/HoshinoNeko.github.io
        ref: master

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.11.0'

    - name: Build and Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEPLOY_REPO: HoshinoNeko/HoshinoNeko.github.io
        DEPLOY_BRANCH: gh-pages
        COMMIT_USER: "GITHUB ACTIONS[Bot]"
        COMMIT_EMAIL: 21078047+HoshinoNeko@users.noreply.github.com
        PUBLISH_DIR: ./public # The folder the action should deploy.
      run: |
        npm install hexo-cli -g
        npm install hexo-deployer-git --save
        npm install hexo-theme-next
        npm install
        hexo clean
        hexo generate
        cd public
        git init
        cp ../CNAME CNAME
        git add .
        git config user.name ${COMMIT_USER}
        git config user.email ${COMMIT_EMAIL}
        git commit -m "Updated by Actions at `date +'%Y-%m-%d %H:%M:%S'`"
        git branch -M ${DEPLOY_BRANCH}
        git remote add origin https://HoshinoNeko:${GITHUB_TOKEN}@github.com/${DEPLOY_REPO}
        git push -u -f origin ${DEPLOY_BRANCH}
