name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
            repository: HoshinoNeko/HoshinoNeko.github.io
            ref: master

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.11.0'

    - name: Build and Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEPLOY_REPO: HoshinoNeko/HoshinoNeko.github.io # The repository the action should deploy to.
        DEPLOY_BRANCH: docs  # The branch the action should deploy to.
        COMMIT_NAME: "GITHUB ACTIONS[Bot]"
        COMMIT_EMAIL: "21078047+HoshinoNeko@users.noreply.github.com"
        COMMIT_MESSAGE: Updated By Actions at {{ now('YYYY-MM-DD HH:mm:ss') }}
        PUBLISH_DIR: ./public # The folder the action should deploy.
      run: |
        npm install hexo-cli -g
        npm install hexo-deployer-git --save
        npm install
        hexo clean
        git config --global user.name '${env.COMMIT_NAME}'
        hexo deploy
